"""Shared Home Assistant class and unit identifiers for Domoticz metrics."""

from __future__ import annotations

STATE_CLASS_MEASUREMENT = "measurement"
STATE_CLASS_TOTAL_INCREASING = "total_increasing"
ENTITY_CATEGORY_DIAGNOSTIC = "diagnostic"
DEVICE_CLASS_BATTERY = "battery"
DEVICE_CLASS_HUMIDITY = "humidity"
DEVICE_CLASS_ILLUMINANCE = "illuminance"
DEVICE_CLASS_POWER = "power"
DEVICE_CLASS_PRESSURE = "atmospheric_pressure"
DEVICE_CLASS_TEMPERATURE = "temperature"
DEVICE_CLASS_VOLTAGE = "voltage"
DEVICE_CLASS_ENERGY = "energy"
DEVICE_CLASS_WATER = "water"
DEVICE_CLASS_PRECIPITATION = "precipitation"
DEVICE_CLASS_PRECIPITATION_INTENSITY = "precipitation_intensity"
DEVICE_CLASS_WIND_SPEED = "wind_speed"
DEVICE_CLASS_CURRENT = "current"
DEVICE_CLASS_FREQUENCY = "frequency"
UNIT_CELSIUS = "celsius"
UNIT_FAHRENHEIT = "fahrenheit"
UNIT_PERCENT = "percent"
UNIT_HPA = "hpa"
UNIT_LUX = "lux"
UNIT_VOLT = "volt"
UNIT_WATT = "watt"
UNIT_KWH = "kwh"
UNIT_M3 = "m3"
UNIT_LITERS = "l"
UNIT_MM = "mm"
UNIT_MM_PER_HOUR = "mm_per_hour"
UNIT_METER_PER_SECOND = "meter_per_second"
UNIT_BAR = "bar"
UNIT_AMPERE = "A"
UNIT_HERTZ = "hz"
